spaces > tabs

diff --git a/bin/dev/setup-secrets b/bin/dev/setup-secrets
--- a/bin/dev/setup-secrets
+++ b/bin/dev/setup-secrets
@@ -10,26 +10,26 @@ SECRETS_REPO_DIR="$APP_DIR/../secrets"
 SECRET_FILE_PATH="${SECRETS_REPO_DIR}/p4hApp-secrets.yml"
 
 main() {
-	if ! [ -x "$(command -v sops)" ]; then
-		echo "Error: could not find 'sops' on system."
-		echo "You will need to make sure that the program 'sops' is installed."
-		exit 1
-	fi
+  if ! [ -x "$(command -v sops)" ]; then
+    echo "Error: could not find 'sops' on system."
+    echo "You will need to make sure that the program 'sops' is installed."
+    exit 1
+  fi
 
-	if ! test -f "$SECRET_FILE_PATH"; then
-		local expected_dir=$(realpath "${APP_DIR}/..")
-		echo "Error: could not find secrets file"
-		echo "You will need to have the secrets repo cloned in ${expected_dir}/"
-		exit 1
-	fi
+  if ! test -f "$SECRET_FILE_PATH"; then
+    local expected_dir=$(realpath "${APP_DIR}/..")
+    echo "Error: could not find secrets file"
+    echo "You will need to have the secrets repo cloned in ${expected_dir}/"
+    exit 1
+  fi
 
-	if [ -z "$SOPS_PGP_FP" ]; then
-		echo "Error: the env SOPS_PGP_FP is not set"
-		echo "You will need to make sure this env is set to the value of the GPG key fingerprint"
-		exit 1
-	fi
+  if [ -z "$SOPS_PGP_FP" ]; then
+    echo "Error: the env SOPS_PGP_FP is not set"
+    echo "You will need to make sure this env is set to the value of the GPG key fingerprint"
+    exit 1
+  fi
 
-	sops -d "$SECRET_FILE_PATH" >"${APP_DIR}/secrets.yml"
+  sops -d "$SECRET_FILE_PATH" >"${APP_DIR}/secrets.yml"
   echo "secrets.yml has been created and set!"
   exit 0
 }
